spring:
  datasource:
    url: jdbc:mysql://localhost:3306/softwarecup
    username: root
    password: 19805601056Bkj@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 19805601056Bkj@@


  ai:
    openai:
      api-key: ${API-KEY-xiaoai}
      base-url: https://xiaoai.plus
      chat:
        options:
          model: gpt-4o-mini
    chat:
      memory:
        repository:
          jdbc:
            platform: mariadb
            initialize-schema: always

    vectorstore:
      neo4j:
        initialize-schema: true
        database-name: neo4j
        index-name: custom-index
        embedding-dimension: 1536
        distance-type: cosine




  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${file.upload-dir} # 将上传目录配置为静态资源路径

file:
  upload-dir: ./uploads # 上传目录路径



