spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prepguide
    username: root
    password: 19805601056Bkj@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: redis://localhost:6379


  ai:
    openai:
      api-key: ${API-KEY-xiaoai}
      base-url: https://xiaoai.plus
      chat:
        options:
          model: gpt-4o-mini
    chat:
      memory:
        repository:
          jdbc:
            platform: mariadb
            initialize-schema: always

    vectorstore:
      redis:
        # 首次启动自动创建索引与 schema
        initialize-schema: true
        index-name: custom-index
#        prefix: kb   #redis里面键的前缀


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.backend.pojo
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true




