spring:
  datasource:
    url: jdbc:mysql://localhost:3306/softwarecup
    username: root
    password: 19805601056Bkj@@
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: redis://localhost:6379


  ai:
    openai:
      api-key: ${API-KEY-xiaoai}
      base-url: https://xiaoai.plus
      chat:
        options:
          model: gpt-4o-mini
    chat:
      memory:
        repository:
          jdbc:
            platform: mariadb
            initialize-schema: always

    vectorstore:
      redis:
        # 首次启动自动创建索引与 schema
        initialize-schema: true
        index-name: custom-index
        prefix: kb




  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:${file.upload-dir} # 将上传目录配置为静态资源路径

file:
  upload-dir: ./uploads # 上传目录路径



